### ISSUE TITLE
Pd4Web can+t compile [else/pitch.shift~]

### ISSUE THREAD

**Issue by luismrguimaraes** [charlesneimog/pd4web#17]
I added the `else/pitch.shift~` object and the patch did not compile. Here is the full log:
```bash
Traceback (most recent call last):
  File "/opt/homebrew/bin/pd4web", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/__init__.py", line 8, in main
    Pd4WebInstance.argParse()
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Pd4Web.py", line 77, in argParse
    self.Execute()
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Pd4Web.py", line 106, in Execute
    self.ExternalsBuilder = GetAndBuildExternals(self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Builder.py", line 21, in __init__
    OK = self.GetObjectsSourceCode()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Builder.py", line 219, in GetObjectsSourceCode
    raise Exception("Could not find " + patchLine.name)
Exception: Could not find pitch.shift~
```
`else/rescale` and `else/blocksize~` compiled right before:
```bash
  🟢️ Found External: blocksize~            | Lib: else
  🟢️ Found External: rescale               | Lib: else
  ```

**Comment by charlesneimog** [comment]
In previous messages I saw that you was using the version 2.0.6 of `pd4web`, update to the current version. This problem was fixed in version `2.0.9`. Use 

`pip install git+https://github.com/charlesneimog/pd4web`.

**Comment by luismrguimaraes** [comment]
I just tried with `2.0.10rc4` and it gives the same error.

**Comment by charlesneimog** [comment]
Try to remove the `build` folder.

If it does not work, you need to give me some info and a way to reproduce it.
Without this it is hard to  understand what is happening. Because I tried to compile it here and it works.

**Comment by charlesneimog** [comment]
Great!
