### ISSUE TITLE
[else/float2sig~] object is not compiling

### ISSUE THREAD

**Issue by luismrguimaraes** [charlesneimog/pd4web#18]
Here is the error I'm getting:
```bash
Traceback (most recent call last):
  File "/opt/homebrew/bin/pd4web", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/__init__.py", line 8, in main
    Pd4WebInstance.argParse()
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Pd4Web.py", line 79, in argParse
    self.Execute()
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Pd4Web.py", line 108, in Execute
    self.ExternalsBuilder = GetAndBuildExternals(self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Builder.py", line 21, in __init__
    OK = self.GetObjectsSourceCode()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Builder.py", line 221, in GetObjectsSourceCode
    raise Exception("Could not find " + patchLine.name)
Exception: Could not find float2sig~
```

I'm using version `2.0.10rc6` and have already tried again after removing the `build/` and the `Pd4Web/` folders.

**Comment by luismrguimaraes** [comment]
Also `else/perlin~`. Let me know if you were already aware of this. I haven't yet seen a list with all the supported objects, so I'm reporting the ones I find.

**Comment by charlesneimog** [comment]
Thank to report! I thought this was resolved, it has to do with abstractions.

All the objects not supported should print an error message, this is not the case for `perlin~` and `float2sig~`, this should be fixed from commit f2eb208e81271236b222ee39c1d930d3717f5802, again you must install using 

```
pip install git+https://github.com/charlesneimog/pd4web
```

**Comment by luismrguimaraes** [comment]
Great, I'll confirm it tomorrow. I also got errors when compiling `[else/db2lin]` and `[cyclone/db2a]`.

**Comment by luismrguimaraes** [comment]
Apparently, for the cyclone object, it's a cmake error.

**Comment by charlesneimog** [comment]
I believe was the same error! Both objects are compiling here! 

Let me know!

**Comment by luismrguimaraes** [comment]
Also, I'm getting CMake errors when I try to use both `else` and `cyclone` libraries.

**Comment by charlesneimog** [comment]
I hope that https://github.com/charlesneimog/pd4web/commit/e1664a8bdcd1eae1bee3a3e38fe9edace1e0b98d will fix it now

**Comment by luismrguimaraes** [comment]
[else/float2sig~] now works, but something like 
```
#N canvas 324 361 899 487 12;
#X obj 358 275 cyclone/dbtoa;
#X obj 289 144 else/float2sig~;
```
does not compile.
Here is my error:
```bash
Traceback (most recent call last):
  File "/opt/homebrew/bin/pd4web", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/__init__.py", line 8, in main
    Pd4WebInstance.argParse()
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Pd4Web.py", line 79, in argParse
    self.Execute()
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Pd4Web.py", line 108, in Execute
    self.ExternalsBuilder = GetAndBuildExternals(self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Builder.py", line 43, in __init__
    self.ConfigureProject()
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Builder.py", line 371, in ConfigureProject
    raise Exception("Error: Could not configure the project")
Exception: Error: Could not configure the project
```
I'm using version `2.1.0.dev2`.
