### ISSUE TITLE
cyclone and else conflits targets

### ISSUE THREAD

**Issue by charlesneimog** [charlesneimog/pd4web#20]
```
#N canvas 324 361 899 487 12;
#X obj 358 275 cyclone/dbtoa;
#X obj 289 144 else/float2sig~;
```
does not compile.
Here is my error:
```bash
Traceback (most recent call last):
  File "/opt/homebrew/bin/pd4web", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/__init__.py", line 8, in main
    Pd4WebInstance.argParse()
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Pd4Web.py", line 79, in argParse
    self.Execute()
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Pd4Web.py", line 108, in Execute
    self.ExternalsBuilder = GetAndBuildExternals(self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Builder.py", line 43, in __init__
    self.ConfigureProject()
  File "/opt/homebrew/lib/python3.11/site-packages/pd4web/pd4web/Builder.py", line 371, in ConfigureProject
    raise Exception("Error: Could not configure the project")
Exception: Error: Could not configure the project
```
I'm using version `2.1.0.dev2`.

_Originally posted by @luismrguimaraes in https://github.com/charlesneimog/pd4web/issues/18#issuecomment-2465150574_

**Comment by charlesneimog** [comment]
It is because cyclone and else have one object with the same name, and then the cmake targets conflicts. 

Conflicts:
`pink~`
`scope~`
`trunc~`
